# Generated by Django 4.2.5 on 2023-11-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('edad', models.IntegerField(max_length=25)),
                ('propuesta', models.CharField(max_length=25)),
            ],
        ),
    ]
