# Generated by Django 4.2.5 on 2023-12-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_railway', '0002_experiencia_delete_propuestas'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='puesto',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
