# Generated by Django 4.2.5 on 2023-12-12 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_railway', '0004_proyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencia',
            old_name='trabajo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='proyecto',
            new_name='nombre',
        ),
    ]
