# Generated by Django 4.2.5 on 2023-12-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_railway', '0006_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
    ]
