# Generated by Django 4.2.5 on 2023-12-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_railway', '0008_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
